---

- name: "Check 'kafka_zookeeper_hosts' variable"
  fail: msg="Playbook execution aborted due to missing or empty required variable 'kafka_zookeeper_hosts'"
  when: kafka_zookeeper_hosts is not defined or kafka_zookeeper_hosts | length == 0

- name: "Check 'kafka_hosts' variable"
  fail: msg="Playbook execution aborted due to missing or empty required variable 'kafka_hosts'"
  when: kafka_hosts is not defined or kafka_hosts == ''

