---
- name: "start kafka"
  service: name=kafka state=started
  sudo: yes

- name: "stop kafka"
  service: name=kafka state=stopped
  sudo: yes

- name: "restart kafka"
  service: name=kafka state=restarted
  sudo: yes

- name: "start zookeeper"
  service: name=zookeeper state=started
  sudo: yes

- name: "stop zookeeper"
  service: name=zookeeper state=stopped
  sudo: yes

- name: "restart zookeeper"
  service: name=zookeeper state=restarted
  sudo: yes

- name: "reload systemctl daemon"
  command: systemctl daemon-reload
  sudo: yes

